# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:11.1.0
pipelines:
  custom: # Pipelines that are triggered manually via the Bitbucket GUI
    init: # -- First time init
    - step:
        caches:
          - node
          - composer
        script:
          - npm install
          - npm install -g @angular/cli
          - ng build --prod
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp init -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST
    deploy-all: # -- Deploys all files from the selected commit
    - step:
        caches:
          - node
          - composer
        script:
          - npm install
          - npm install -g @angular/cli
          - ng build --prod
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp init -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST --all
  branches: # Automated triggers on commits to branches
    master: # -- When committing to master branch
    - step:
        deployment: production
        caches:
          - node
          - composer
        script:
          - npm install
          - npm install -g @angular/cli
          - ng build --prod
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp init -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ftp://$FTP_HOST